#!/bin/bash
# This creates a minimal gradle-wrapper.jar by calling gradle wrapper
# We'll do this in the CI environment where gradle is available

mkdir -p gradle/wrapper

# Create minimal wrapper files
cat > gradle/wrapper/gradle-wrapper.properties << 'PROPS'
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
PROPS

echo "Wrapper properties created. Jar will be generated by CI using 'gradle wrapper' command."
