ALTER TABLE products
ADD COLUMN IF NOT EXISTS "isFeatured" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "isRecommended" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "isVisible" BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS "fileType" TEXT,
ADD COLUMN IF NOT EXISTS "weight" TEXT,
ADD COLUMN IF NOT EXISTS "colors" JSONB,
ADD COLUMN IF NOT EXISTS "sizes" JSONB,
ADD COLUMN IF NOT EXISTS "sku" TEXT,
ADD COLUMN IF NOT EXISTS "shippingFee" NUMERIC,
ADD COLUMN IF NOT EXISTS "estimatedDelivery" TEXT;
